sudo: required
services:
  - docker

before_install:
  - docker build -t lincwest/react-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lincwest/react-test npm test -- --coverage

after_success:
  - docker build -t lincwest/multi-client ./client
  - docker build -t lincwest/multi-nginx ./nginx
  - docker build -t lincwest/multi-server ./server
  - docker build -t lincwest/multi-worker ./worker
# log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take those images and push them to docker hub
  - docker push lincwest/multi-client
  - docker push lincwest/multi-nginx
  - docker push lincwest/multi-server
  - docker push lincwest/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-634445229035
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
